version: '3.5'

services:
  postgres-compose:
    image: postgres:15
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "mydb"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network
    command: -p 5432

networks:
  postgres-compose-network:
    driver: bridge