spring:
    datasource:
        password: postgres
        url: jdbc:postgresql://localhost:5432/mydb
        username: postgres
    jpa:
        database-plataform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
                show_sql: true
    flyway:
        enabled: true
        baseline-on-migrate: true
        locations: "classpath:db.migration"
        validateMigrationNaming: true

    graphql:
        graphiql:
            enabled: true

token:
    signing:
        key: "EjuuIryX3ezEuVOpsytW45bbmfdFHopNfS0wQyFNG6H4Hnsc"
